/**
 * Module:   tests/lib/databaseRowExports.spec.ts
 * Project:  A Penny For Our Thoughts
 * Created:  May 2026 (BUG-022 — DB types regenerate drift)
 * Summary:  Asserts the *Row re-export contract between
 *           src/types/database.ts (the schema source-of-truth, partially
 *           auto-generated by `supabase gen types typescript`) and
 *           src/lib/db.ts (which imports `*Row` aliases by name).
 *
 *           The `*Row` aliases are HAND-MAINTAINED in database.ts —
 *           the Supabase type-generator doesn't produce them. The
 *           .github/workflows/migrate.yml workflow regenerates the file
 *           on every migration. If it forgets to re-append the alias
 *           block (or if a new table is added without its corresponding
 *           Row alias), every db.ts import breaks and the next deploy
 *           fails at the type-check step.
 *
 *           This test fails LOUDLY at the test-runner stage so the
 *           failure is caught in PR review rather than at deploy time.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

// Resolve absolute paths to the two source files this spec reads. Vitest
// runs under Node ESM where __dirname isn't defined; we synthesise it from
// import.meta.url so the spec works regardless of where vitest is launched.
const __dirname = dirname(fileURLToPath(import.meta.url));
const dbTsPath       = join(__dirname, '../../src/lib/db.ts');
const databaseTsPath = join(__dirname, '../../src/types/database.ts');

/**
 * Pull every identifier ending in `Row` from db.ts's type-import block.
 *   - Matches `ProfileRow,` `WishlistItemRow` etc. inside the
 *     `import type { ... } from '@/types/database';` block.
 *   - Excludes any `Row` that happens to appear elsewhere (function bodies,
 *     comments, etc.) by scoping to the type-import block.
 */
function importedRowNames(): string[] {
  const src = readFileSync(dbTsPath, 'utf8');
  const m = src.match(/import type \{([\s\S]*?)\} from '@\/types\/database'/);
  expect(m, 'db.ts should have a `import type { ... } from "@/types/database"` block').toBeTruthy();
  const block = m![1];
  const matches: string[] = [];
  for (const match of block.matchAll(/\b(\w+Row)\b/g)) matches.push(match[1]);
  return matches.sort();
}

/**
 * Pull every `export type *Row = ...` identifier from database.ts.
 */
function exportedRowNames(): string[] {
  const src = readFileSync(databaseTsPath, 'utf8');
  const matches: string[] = [];
  for (const match of src.matchAll(/^export type (\w+Row)\b/gm)) matches.push(match[1]);
  return matches.sort();
}

describe('BUG-022 — *Row export contract between db.ts and database.ts', () => {
  it('every Row name imported by db.ts is exported by database.ts', () => {
    const imported = importedRowNames();
    const exported = new Set(exportedRowNames());

    expect(imported.length, 'db.ts should import at least one Row alias').toBeGreaterThan(0);

    const missing = imported.filter((n) => !exported.has(n));
    expect(
      missing,
      `database.ts is missing export(s) that db.ts imports — likely because the file was regenerated ` +
      `by \`supabase gen types typescript\` without re-appending the hand-maintained alias block. ` +
      `See migrate.yml's "Re-append *Row aliases" step.`,
    ).toEqual([]);
  });

  it('database.ts exports at least 17 Row aliases (one per current table)', () => {
    // Sanity check — if the count drops, someone likely regenerated and
    // forgot to re-append. If the count grows, that's fine (new table added).
    const exported = exportedRowNames();
    expect(exported.length).toBeGreaterThanOrEqual(17);
  });

  it('the hand-maintained block carries a BUG-022 marker comment', () => {
    // If the marker comment ever disappears, the regenerate workflow was
    // run without the "Re-append *Row aliases" step — surface that loudly.
    const src = readFileSync(databaseTsPath, 'utf8');
    expect(
      src,
      'database.ts should contain a "BUG-022" or "HAND-MAINTAINED RE-EXPORTS" marker ' +
      'near the *Row alias block — see the bug entry in PHASE_TRACKING.md.',
    ).toMatch(/BUG-022|HAND-MAINTAINED RE-EXPORTS/);
  });
});
